// Polyfill ElementInternals for happy-dom which does not implement attachInternals.
// This only runs in the test environment and has no effect in real browsers.
if (!('attachInternals' in HTMLElement.prototype)) {
  Object.defineProperty(HTMLElement.prototype, 'attachInternals', {
    configurable: true,
    writable: true,
    value(): ElementInternals {
      return {
        setFormValue: () => {},
        setValidity: () => {},
        checkValidity: () => true,
        reportValidity: () => true,
        form: null,
        validity: {
          badInput: false,
          customError: false,
          patternMismatch: false,
          rangeOverflow: false,
          rangeUnderflow: false,
          stepMismatch: false,
          tooLong: false,
          tooShort: false,
          typeMismatch: false,
          valid: true,
          valueMissing: false,
        },
        validationMessage: '',
        willValidate: false,
        labels: null as unknown as NodeList,
        shadowRoot: null,
        role: null,
        ariaAtomic: null,
        ariaAutoComplete: null,
        ariaBusy: null,
        ariaChecked: null,
        ariaColCount: null,
        ariaColIndex: null,
        ariaColSpan: null,
        ariaCurrent: null,
        ariaDescription: null,
        ariaDisabled: null,
        ariaExpanded: null,
        ariaHasPopup: null,
        ariaHidden: null,
        ariaInvalid: null,
        ariaKeyShortcuts: null,
        ariaLabel: null,
        ariaLevel: null,
        ariaLive: null,
        ariaModal: null,
        ariaMultiLine: null,
        ariaMultiSelectable: null,
        ariaOrientation: null,
        ariaPlaceholder: null,
        ariaPosInSet: null,
        ariaPressed: null,
        ariaReadOnly: null,
        ariaRequired: null,
        ariaRoleDescription: null,
        ariaRowCount: null,
        ariaRowIndex: null,
        ariaRowSpan: null,
        ariaSelected: null,
        ariaSetSize: null,
        ariaSort: null,
        ariaValueMax: null,
        ariaValueMin: null,
        ariaValueNow: null,
        ariaValueText: null,
        ariaRelevant: null,
        setCustomValidity: () => {},
      } as unknown as ElementInternals
    },
  })
}
